#pragma once

#define _USE_MATH_DEFINES
#include <math.h> 
#include <glad/glad.h>
#include <glfw3.h>
#include "Shader.h"
#include "Matrix.h"
#include "Vector.h"
#include "Sprite.h"
#include "Input.h"
#include "GameObject.h"
#include "Behavior.h"
#include "ParticleObject.h"
#include "ColorAffector.h"
#include "SizeAffector.h"
#include "GravityAffector.h"
#include "SpeedAffector.h";
#include "PulsingAffector.h"
#include "NoiseAffector.h"
#include "RotationAffector.h"
#include "CircleRingEmitterShape.h"
#include "CircleEmitterShape.h"
#include "QuadEmitterShape.h"
#include "ParticleSystem.h"
#include "Scene.h"
#include "Audio.h"
#include "ColliderManager.h"
#include "Collider.h"